# -*- coding: utf-8 -*-
"""crop recom algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_uqv6WnJ4YqzixWAWSEnXiBextGd-5Oh
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#read the data
df=pd.read_csv("/content/Crop_recommendation  (1).csv")
df.head()

df.info()